changelog:
  categories:
    - title: "New Features"
      labels:
        - enhancement
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Extensions"
      labels:
        - extensions
    - title: "Documentation"
      labels:
        - documentation
    - title: "Maintenance"
      labels:
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"
